### ISSUE TITLE
Enable/Disable the field from the formField

### ISSUE THREAD

**Issue by donpaul120** [nwagu/forms#11]
Would be nice if i could disable or enable the formField directly from the FormField

**Comment by nwagu** [comment]
If you mean to enable/disable validation for a formField, yea would be nice. For now, you could work around it by adding/removing the form field from the form, and then enabling/disabling the UI element.

You are also welcome to send a PR!

**Comment by donpaul120** [comment]
No i mean, being able to directly disable the formField which also disables the view form being able to get edited... let me know what you think about that.

**Comment by nwagu** [comment]
The formfields are meant to be part of the ViewModel, decoupled from the UI. So no, it can't do that sorry

**Comment by donpaul120** [comment]
No, you don't seem to understand, i'm not asking that the view coupled with the formField. it's the same way we have error(live-data) etc, we should be able to provide events for other states.

such that within the viewModel i can control the logic of disabling the formField or enabling it, like you said it's meant to be part of the viewmodel.

However the workaround is to provide a boolean field in the viewModel and bind that to the view.
